export const GET_STATES = "GET_STATES"
export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS"
export const GET_STATES_FAILED = "GET_STATES_FAILED"

export const GET_MUNICIPALITIES = "GET_MUNICIPALITIES"
export const GET_MUNICIPALITIES_SUCCESS = "GET_MUNICIPALITIES_SUCCESS"
export const GET_MUNICIPALITIES_FAILED = "GET_MUNICIPALITIES_FAILED"
