export const GET_PRODUCT_SIZES = "GET_PRODUCT_SIZES"
export const GET_PRODUCT_SIZES_SUCCESS = "GET_PRODUCT_SIZES_SUCCESS"
export const GET_PRODUCT_SIZES_FAILED = "GET_PRODUCT_SIZES_FAILED"

export const GET_PRODUCT_SIZE = "GET_PRODUCT_SIZE"
export const GET_PRODUCT_SIZE_SUCCESS = "GET_PRODUCT_SIZE_SUCCESS"
export const GET_PRODUCT_SIZE_FAILED = "GET_PRODUCT_SIZE_FAILED"

export const REGISTER_PRODUCT_SIZE = "REGISTER_PRODUCT_SIZE"
export const REGISTER_PRODUCT_SIZE_SUCCESS = "REGISTER_PRODUCT_SIZE_SUCCESS"
export const REGISTER_PRODUCT_SIZE_FAILED = "REGISTER_PRODUCT_SIZE_FAILED"

export const UPDATE_PRODUCT_SIZE = "UPDATE_PRODUCT_SIZE"
export const UPDATE_PRODUCT_SIZE_SUCCESS = "UPDATE_PRODUCT_SIZE_SUCCESS"
export const UPDATE_PRODUCT_SIZE_FAILED = "UPDATE_PRODUCT_SIZE_FAILED"

export const UPDATE_PRODUCT_SIZE_LIST = "UPDATE_PRODUCT_SIZE_LIST"
export const UPDATE_PRODUCT_SIZE_LIST_SUCCESS = "UPDATE_PRODUCT_SIZE_LIST_SUCCESS"
export const UPDATE_PRODUCT_SIZE_LIST_FAILED = "UPDATE_PRODUCT_SIZE_LIST_FAILED"
