export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED"

export const GET_ORDER = "GET_ORDER"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILED = "GET_ORDER_FAILED"

export const REGISTER_ORDER = "REGISTER_ORDER"
export const REGISTER_ORDER_SUCCESS = "REGISTER_ORDER_SUCCESS"
export const REGISTER_ORDER_FAILED = "REGISTER_ORDER_FAILED"

export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED"
