export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED"

export const GET_ORDER = "GET_ORDER"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILED = "GET_ORDER_FAILED"

export const REGISTER_ORDER = "REGISTER_ORDER"
export const REGISTER_ORDER_SUCCESS = "REGISTER_ORDER_SUCCESS"
export const REGISTER_ORDER_FAILED = "REGISTER_ORDER_FAILED"

export const NEXT_STATUS_ORDER = "NEXT_STATUS_ORDER"
export const RESUME_ORDER = "RESUME_ORDER"
export const PRINT_ORDER = "PRINT_ORDER"

export const CUSTOM_ORDER_SUCCESS = "CUSTOM_ORDER_SUCCESS"
export const CUSTOM_ORDER_FAILED = "CUSTOM_ORDER_FAILED"

export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED"

export const GET_DELIVERY_METHODS = "GET_DELIVERY_METHODS"
export const GET_DELIVERY_METHODS_SUCCESS = "GET_DELIVERY_METHODS_SUCCESS"
export const GET_DELIVERY_METHODS_FAILED = "GET_DELIVERY_METHODS_FAILED"

export const GET_DELIVERY_QUOTE = "GET_DELIVERY_QUOTE"
export const GET_DELIVERY_QUOTE_SUCCESS = "GET_DELIVERY_QUOTE_SUCCESS"
export const GET_DELIVERY_QUOTE_FAILED = "GET_DELIVERY_QUOTE_FAILED"

export const RESET_CAR = "RESET_CAR"
export const UPDATE_CAR = "UPDATE_CAR"