export const BOOLEAN_STRING = {
    YES: 'Si',
    NO: 'No'
}

export const STATUS = {
    ACTIVE: true,
    INACTIVE: false
};


//FIELD OPTIONS GROUPS
export const GROUPS = {
    REFERENCE_KEY: 'REFERENCE_KEY',
    MATERIALS: 'MATERIALS',
    PROVIDERS: 'PROVIDERS',
    ORDERS_ORIGIN: 'ORDERS_ORIGIN',
};
//FIELD OPTIONS NAMES
export const NAMES = {
    PRODUCT: 'PRODUCT',
};

export const DELIVERY_TYPES = {
    PREVIOUS_PAYMENT: 'PREVIO PAGO',
    PAY_ONLY_DELIVERY: 'PREVIO PAGO COD',
    CHARGE_ON_DELIVERY: 'CONTRA ENTREGA',
};

export const DELIVERY_METHODS_PAYMENT_TYPES = ['MENSAJERO'];

export const PAYMENT_TYPES = {
    CASH: 'EFECTIVO',
    TRANSFER: 'TRANSAFERENCIA',
};
