export const GENERATE_REPORT = "GENERATE_REPORT"
export const GENERATE_REPORT_SUCCESS = "GENERATE_REPORT_SUCCESS"
export const GENERATE_REPORT_FAILED = "GENERATE_REPORT_FAILED"
export const GENERATE_REPORT_RESTART = "GENERATE_REPORT_RESTART"
